name: StrikeOne Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  execute_so_test:

    runs-on: self-hosted

    steps:
    - name: StrikeOne Test Execution
      id: strikeone_test_execution
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://assessment.strikeone.io/api/vm/tests/external/execute"
        method: "POST"
        customHeaders: '{"Content-Type": "application/json"}'
        bearerToken: ${{ secrets.SO_API_TOKEN }}
        data: '{"externalData": { "parsedDomainId": "188800312", "parsedScanId": "188800401", "tool": "sonarqube", "testName": "Test SonarQube from GitHub Actions" }, "toolData": { "projectUrl": "https://github.com/aleHRevirtus/DVWA.git", "projectName": "DVWA", "address": "http://172.18.0.3:9001" }}'
    - name: Show Response
      run: |
        echo ${{ steps.strikeone_test_execution.outputs.response }}
